### ISSUE TITLE
Stage 3 Tracking

### ISSUE THREAD

**Issue by bmeck** [tc39/proposal-upsert#22]
- [x] Complete Spec Text
- [ ] Editorial Committee Review
- [ ] Specification Reviewers
    - @michaelficarra 
    - Need Volunteers

**Comment by ljharb** [comment]
https://github.com/tc39/notes/blob/7b2de881081abd34b02bc87bcdb662fd97555795/meetings/2019-10/october-2.md#conclusionresolution-5 indicates that the reviewers are @michaelficarra and @gibson042

**Comment by bmeck** [comment]
that was soo long ago XD might want new volunteers

**Comment by michaelficarra** [comment]
October, 2019 is a long time ago? That's only like 5 meetings ago.

**Comment by bmeck** [comment]
@michaelficarra you are now on the list again

**Comment by ljharb** [comment]
@bmeck stage 3 reviewers are generally only selected in plenary.

**Comment by dminor** [comment]
We're making updates to the specification text, so we'll have to start the process of tracking Stage 2.7 from the beginning.
