### ISSUE TITLE
find a new name

### ISSUE THREAD

**Issue by bmeck** [tc39/proposal-upsert#29]

**Comment by bmeck** [comment]
Ideas:

Term | Definition
---- | ----
`requisition()`|  "demand the performance or occurrence of."
`ensure()` | "make certain of obtaining or providing (something)."

**Comment by papb** [comment]
I like `ensure` :+1:

**Comment by ljharb** [comment]
`insertOnDuplicateKeyUpdate` is what mysql calls it; in https://www.npmjs.com/package/global-cache i called it `setIfMissingThenGet`.

Both names are descriptive and terrible. I'm not sure what short name will be descriptive and non-terrible, though :-/

**Comment by gibson042** [comment]
It might be possible to get away with just `update`, as in "update the map data".
* handler-object style: `map.update(key, { replace(oldValue, key, map){…}, add(key, map){…} })`
* callback style: `map.update(key, (oldValue, key, map) => …, (key, map) => …)`

**Comment by dleeftink** [comment]
Possibly, a three letter descriptor to stay true to `get` / `set` / `has`:

- `alt` : alter
- `mod` : modify 
- `fix` : fixing a key
- `fit` : (re)fitting a key
- `for` : as in, map.for('key',  ... 
- `pin` : pinning down
- `rec` : rectify, record
- `ref` : reference, reform, refine
- `tie` : tie down / when keys are tied

`map.fit`, `map.rec` and `map.tie` cover quite some  ground regarding the current proposal.

In case of 4 char names, `edit` or `over` (overwrite) may function as shorter alternatives to `update`.

**Comment by dminor** [comment]
Closing in favour of https://github.com/tc39/proposal-upsert/issues/60.
