### ISSUE TITLE
req: WeakMap.emplace

### ISSUE THREAD

**Issue by runspired** [tc39/proposal-upsert#52]
I would love for this capability to exist with WeakMap's as well. I end up using this pattern quite often for both Map's and WeakMaps.

```ts
const Records = new WeakMap();

function getRecord(key) {
  let record = Records.get(key);
  if (!record) {
    record = new Record();
    Records.set(key, record);
  }
  
  return record;
}
```

**Comment by LinusU** [comment]
This proposal proposes to add `emplace` both to `Map` and `WeakMap` already :tada:

https://github.com/tc39/proposal-upsert/blob/d1daff560e3d53abd996099ee3da674374ea9226/spec.emu#L39-L58
