### ISSUE TITLE
Additional examples to single update function with upsert functionality

### ISSUE THREAD

**Issue by malthe** [tc39/proposal-upsert#54]
Under "Why not have a single function that updates the value if no if the key is mapped?", instead of using a try/finally clause, we could write:

```javascript
counts.emplace(key, (existing) => existing ?? 0 + 1)
```

Factory with just insertion:
```javascript
counts.emplace(key, (existing) => existing ?? someFactory());
```
Insertion and update, assuming the created value here is always truthy, a reasonable assumption.
```javascript
counts.emplace(key, (existing) => existing && doSomething(existing) || someFactory())
```
I don't think these examples are adequately presented in the proposal.

**Comment by dminor** [comment]
The new direction for the proposal is only looking at the insert use case, not updates.
