### ISSUE TITLE
clarification on key ordering when updating

### ISSUE THREAD

**Issue by runspired** [tc39/proposal-upsert#57]
since Map keeps track of key-insertion order, I feel this spec should define key-order semantics for `update` as there are two possible outcomes:

- update results in removal of current key and insertion of that key at the end
- update results in no change to the current key position

I suspect the obvious choice is to maintain the current key position, but that it would be best to be explicit about it.

**Comment by dminor** [comment]
We're going in a different direction with this proposal that no longer includes updating, but this is a valid point to consider if we revisit the update use case in the future.
